embed_model: sentence-transformers/all-MiniLM-L6-v2
embed_dim: 384

# chunking
chunk_size: 800
chunk_overlap: 128

faiss_index_path: models/faiss.index
docs_store_path: models/docs.jsonl

generator_model: mistralai/Mistral-7B-Instruct-v0.1
generator_device: -1  # -1 for cpu, >=0 for cuda device id

use_agentic: true
